In [1]:

import torch
import numpy as np

In [5]:
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)
test2 = torch.randn(3, 3)  
print(test2)  
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
tensor([[-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731]])
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
