In [1]:

import torch
import numpy as np

In [5]:
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)
test2 = torch.randn(3, 3)  
print(test2)  
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
tensor([[-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731]])
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])


In [ ]:
test3 = test1+test2
test4 = test1*4
print(test3)
print(test4)
print(test4.shape)
#Other Math functions
#abs, asin, det, avd, std_mean, max

tensor([[ 1.1377, -0.8901, -1.9968],
        [-0.2882,  0.0161, -2.4698],
        [ 0.5260,  0.2717, -0.3461]])
tensor([[ 6.1640, -1.1737, -8.7152],
        [ 2.2737, -4.3381, -5.5944],
        [ 1.6134,  3.3521, -2.8770]])
torch.Size([3, 3])
