In [2]:

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [5]:
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)
test2 = torch.randn(3, 3)  
print(test2)  
torch.manual_seed(0)
test1 = torch.randn(3, 3)
print(test1)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
tensor([[-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731]])
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])


In [ ]:
test3 = test1+test2
test4 = test1*4
print(test3)
print(test4)
print(test4.shape)
#Other Math functions
#abs, asin, det, avd, std_mean, max
#Note, range of rand vs randn and operations you can do to change its range

tensor([[ 1.1377, -0.8901, -1.9968],
        [-0.2882,  0.0161, -2.4698],
        [ 0.5260,  0.2717, -0.3461]])
tensor([[ 6.1640, -1.1737, -8.7152],
        [ 2.2737, -4.3381, -5.5944],
        [ 1.6134,  3.3521, -2.8770]])
torch.Size([3, 3])


In [ ]:
#Recurral Network example RNN
x = torch.randn(1, 10) #the input
prev_h = torch.randn(1, 20) #hidden state of rnn that gives it its memory
w_x = torch.randn(20, 10, requires_grad=True) #learning input for hidden state
#requires_grad enables gradient tracking for .backwards
w_h = torch.randn(20, 20, requires_grad=True) #learning weight for input
#MM = matrix multiplication
#.t() is the transpose of a matrix (swaps the dimensions) (why the transpose?)
i2h = torch.mm(w_x, x.t())
h2h = torch.mm(w_h, prev_h.t())
next_h = i2h + h2h #adding output of two matrix multiplications together
next_h = next_h.tanh() #applying activation function, hyperbolic tangent
loss = next_h.sum() #loss function, difference between correct output and predicted output
loss.backward() #backpropagation, smth to do with gradients, derivatives or smth



RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
#Building modeles in pytorch




