Following: https://www.youtube.com/watch?v=V_xro1bcAuA&list=PLy7VBe6V8If6tRUtIjo8nzCsLa6PTKeCe&index=8 plus other resources
Pytorch Fundamentals
Google doc link to notes: https://docs.google.com/document/d/1U5abbSzZvI6JGDtnuu2W8OisjzJU-0dkfZh0DvNB4Uo/edit?tab=t.0 
Note: Figure out the markdown syntax to make prettier/easier to read

Might need to transition to google collab based on GPU/TPU acceleration requirements etc
Rn: the tutorial uses hardware accelerator with GPU
(Google Collab Specific code~using their gpu) !nividia-smi

In [ ]:
import torch #for all pytorch stuff
import random
torch.__version__ 
import torch.nn as nn #parent object of pytorch modules
import torch.nn.functional as F #activation function
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#Tensors
#commonly captilized 
#scalar, vector, matrix, tensor - 0D, 1D, 2D, nD
TENSORBOB = torch.tensor([[1, 2, 3], [1, 4, 5]]) 
TENSORBOB.shape, TENSORBOB.dtype #use comma, or only output last one

torch.int64

In [ ]:
#Often, machine starts with randomized tensors then optimizes
RANDTENSOR = torch.rand(1, 9, 4)
RANDTENSOR2 = torch.rand(1, 9, 4, dtype=torch.float16, device=None, requires_grad=False)
#defaults to none (CPU), gradiant means operations tracked for optimization 
ZEROTENSOR = torch.zeros(1, 9, 4)
ZEROTENSOR2 = torch.zeros_like(RANDTENSOR2)
RANGTENSOR = torch.arange(1, 10, 0.5) #start, end, step amount
RANDTENSOR.dtype, ZEROTENSOR.dtype, ZEROTENSOR2.dtype, RANDTENSOR2.device, RANDTENSOR2.requires_grad

(torch.float32, torch.float32, torch.float16)

Tensor datatypes
- apart from float, int, etc 
- Some are specific for CPU or GPU ie) torch.cuda is GPU (NVIDIA - CUDA)
- precision numberes, 8, 16, 32, 64 - more bits/precision/less speed
Common issues: 
- tensor shapes dont match
- datatype dont match
- device dont match

In [ ]:
#Tensor manipulation
RT = torch.rand(2, 3)
RT, RT+2, RT*2, RT-2, RT/2, RT**2, torch.log(RT), torch.sin(RT) #(cos, tan, etc)

In [ ]:
#Matrix multiplication refresher
RT=torch.rand(2, 3)
RT2=torch.rand(3, 2)
RT3=torch.rand(2, 3)
#doing RT*RT2 wouldn't work, is element wise
torch.matmul(RT, RT2), torch.matmul(RT, torch.transpose(RT3, 0, 1)) #for 2D can do .mm, RT3.T for 2D
#RT.permute for full control of order of tranpose dimensions when larger than 3D 

In [12]:
#Aggregiation
RT=torch.rand(2, 3)
#Both work, but torch. is more common, also only torch.max(...) can do two tensor comparision
#Can specify torch.mean(x.type(float32))
RT, RT.max(), torch.max(RT), RT.mean(), torch.mean(RT), RT.sum(), torch.sum(RT), RT.max(dim=0), torch.max(RT, dim=0), torch.argmax(RT) #index

(tensor([[0.9147, 0.2036, 0.2018],
         [0.2018, 0.9497, 0.6666]]),
 tensor(0.9497),
 tensor(0.9497),
 tensor(0.5230),
 tensor(0.5230),
 tensor(3.1383),
 tensor(3.1383),
 torch.return_types.max(
 values=tensor([0.9147, 0.9497, 0.6666]),
 indices=tensor([0, 1, 1])),
 torch.return_types.max(
 values=tensor([0.9147, 0.9497, 0.6666]),
 indices=tensor([0, 1, 1])))

In [ ]:
#Reshape, Stacking, Squeezing, Unsqueezing, change tensor type
T2 = torch.tensor([[1, 4, 5]]) 
T1 = torch.tensor([[1, 2, 3], [1, 4, 5]], dtype=torch.float16) 
T1 = T1.type(torch.float32)
TRESHAPE = T1.reshape(3, 2)  #(T1.reshape(3, -1))Must have same amount of elements, -1 for automatic size only for 1 dimension of it - can also use .view but worse only for contiguous & changes original tensor
TSTACK = torch.stack([T1, T1, T1, T1], dim=1) #same shape tensors to stack
T3 = T2.squeeze() #removes dimensions of size 1, can specify dims
T4 = T2.unsqueeze(dim=0) #adds dimension of size 1, can specify dims
T1.dtype, T1, TRESHAPE, TSTACK, T2, T3, T4

(torch.float32,
 tensor([[1., 2., 3.],
         [1., 4., 5.]]),
 tensor([[1., 2.],
         [3., 1.],
         [4., 5.]]),
 tensor([[[1., 2., 3.],
          [1., 2., 3.],
          [1., 2., 3.],
          [1., 2., 3.]],
 
         [[1., 4., 5.],
          [1., 4., 5.],
          [1., 4., 5.],
          [1., 4., 5.]]]),
 tensor([[1., 4., 5.]], dtype=torch.float16),
 tensor([1., 4., 5.], dtype=torch.float16),
 tensor([[[1., 4., 5.]]], dtype=torch.float16))

In [33]:
#Indexing
T1 = torch.tensor([[[1, 2, 3], [1, 4, 5]], [[4, 2, 4], [1, 4, 9]]]) 
#Syntax: "[x:y:z]" (start:stop:step), so [:] means everything, [1:6:2] means 1, 3, 5
T1.shape, T1, T1[0][0], T1[0, 0], T1[:, 1], T1[:, 0, :], T1[:, 0, 0], T1[0][0][1:2:1]

(torch.Size([2, 2, 3]),
 tensor([[[1, 2, 3],
          [1, 4, 5]],
 
         [[4, 2, 4],
          [1, 4, 9]]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]),
 tensor([[1, 4, 5],
         [1, 4, 9]]),
 tensor([[1, 2, 3],
         [4, 2, 4]]),
 tensor([1, 4]),
 tensor([2]))

In [ ]:
#Pytorch Numpy interaction
array = np.array([1, 2, 3]) 
tensor = torch.from_numpy(array) #Note, makes copy, not same memory
array2 = tensor.numpy()
array, tensor, array2

(array([1, 2, 3]), tensor([1, 2, 3]), array([1, 2, 3]))

In [ ]:
torch.manual_seed(42) #for reproducibility of random things like torch.rand

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
